<h3><a href="tarea1.html">Tarea 1</a> Tarea numero 1 nombre de usuario </h3>
<h3><a href="tarea2.html">Tarea 2</a> Tarea numero 2 suma de dos numeros </h3>
<h3><a href="tarea3.html">Tarea 3</a> Tarea numero 3 resta de dos numeros </h3>
<h3><a href="tarea4.html">Tarea 4</a> Tarea numero 4 multiplicacion de dos numeros </h3>
<h3><a href="tarea5.html">Tarea 5</a> Tarea numero 5 division de dos numeros </h3>
<h3><a href="tarea6.html">Tarea 6</a> Tarea numero 6 nombre y edad </h3>
<h3><a href="tarea7.html">Tarea 7</a> Tarea numero 7 determina que numero es mayor </h3>
<h3><a href="tarea8.html">Tarea 8</a> Tarea numero 8 determina que numero es menor </h3>
<h3><a href="tarea9.html">Tarea 9</a> Tarea numero 9 determina si el numero es par o impar </h3>
<h3><a href="tarea10.html">Tarea 10</a> Tarea numero 10 Saca el promedio de notas </h3>
<h3><a href="tarea11.html">Tarea 11</a> Tarea numero 11 Determina si aprobo o reprobo </h3>
<h3><a href="tarea12.html">Tarea 12</a> Tarea numero 12 Calcula el area </h3>
<h3><a href="tarea13.html">Tarea 13</a> Tarea numero 13 Calcula el perimetro de un cuadrado </h3>
<h3><a href="tarea14.html">Tarea 14</a> Tarea numero 14 Metros a centimetros </h3>
<h3><a href="tarea15.html">Tarea 15</a> Tarea numero 15 Convierte grados celsius a fahrenheit </h3>
<h3><a href="tarea16.html">Tarea 16</a> Tarea numero 16 Salario total </h3>
<h3><a href="tarea17.html">Tarea 17</a> Tarea numero 17 Descuento del 10% </h3>
<h3><a href="tarea18.html">Tarea 18</a> Tarea numero 18 Factura </h3>
<h3><a href="tarea19.html">Tarea 19</a> Tarea numero 19 Tabla de multiplicar </h3>
<h3><a href="tarea20.html">Tarea 20</a> Tarea numero 20 Suma desde el numero ingresado </h3>
<h3><a href="tarea21.html">Tarea 21</a> Tarea numero 21 Cantidad de letras </h3>
<h3><a href="tarea22.html">Tarea 22</a> Tarea numero 22 Conversion a euros </h3>
<h3><a href="tarea23.html">Tarea 23</a> Tarea numero 23 IVA incliudo </h3>
<h3><a href="tarea24.html">Tarea 24</a> Tarea numero 24 Edad futura </h3>
<h3><a href="tarea25.html">Tarea 25</a> Tarea numero 25 Informacion ingresada </h3>
